### ISSUE TITLE
How to do !==

### ISSUE THREAD

**Issue by aintnorest** [yahoo/cerebro#1]
How would I do region !== 'eu' as rule? Would I need to use a custom evaluator?

**Comment by aintnorest** [comment]
ReadMe could be better had to look at the tests to figure out how to get the customEvaluator to work. Adding the code I used just incase someone else needs similar but it would be nice if !== didn't require a custom evaluator.

`
const context = {
      region: 'eu',
    };

    // resolve configuration
    const customEvaluators = {
      regionIsNotEU(contextKey, testValue) {
        return testValue !== 'eu';
      },
    };
    const experienceConfig = {
        setting: 'logo',
        value: 'blue,
        except: [
            value: 'green',
            region: {
                evaluator: 'regionIsNotEU',
                dimensionValue: 'region'
            },
        ]
    };
    const cerebro = new Cerebro(experienceConfig, { customEvaluators });
    const resolvedExperienceConfig = cerebro.resolveConfig(context)._resolved;
`

**Comment by scsper** [comment]
Hi @aintnorest, 

You should be able to do something like this:

```
const experienceConfig = {
  setting: 'logo',
  value: 'green',
  except: [{
    value: 'blue',
    region: 'eu'
  }]
}
```

I'm really sorry for the late reply on this and that you had to struggle with the documentation to get it to work.  I just started a new job today, so things have been pretty hectic this morning.  

Please let me know if the above snippet doesn't work for you.

**Comment by aintnorest** [comment]
would that code make the logo blue if region === eu? I was looking for region !== eu? I put code above that worked just had to use the customEvaluators.

No worries I worked on a couple different things today so didn't struggle to long and I understand new jobs and just real life.

**Comment by scsper** [comment]
Yeah, it would make the logo blue if the region === eu.  

Your example, however, made the logo green if the region !== eu, and blue if the region === eu.  By setting the default value to 'green', you basically say "make the logo green for any region that is not eu."

**Comment by aintnorest** [comment]
Was a simplified example. If its eu it looks one way( actual also depends on country sometimes), if its one of several other regions is another,  if there is no region it another value, it gets pretty crazy. I'm transferring a if block with two switch cases with if else blocks in the default and some of the cases themselves. It's not great lol.

**Comment by scsper** [comment]
closing the issue for now.  please re-open if you want to discuss this more or if you want to discuss a plan to make it better!
