### ISSUE TITLE
RFC: Configuration polling

### ISSUE THREAD

**Issue by juandopazo** [yahoo/cerebro#15]
# RFC: Configuration polling

## Summary

Applications using Cerebro normally require doing a full deployment to update configuration, as the Cerebro API favors sharing an instance of `new Cerebro()` between requests. This can be very slow to reach production in certan circumstances. To avoid this, we would like the ability to deploy configuration changes separately from the application deployment.

## Requirements

1. Configuration changes should be under version control, in the same files as regular config, not on ad-hoc UIs.
1. Scheduled processes such as cron jobs should be able to do the fetching instead of relying solely on network requests from Node.js.

Requirement (1) does not seem to set any constrains on the Cerebro API. It is something that can be achieved with the right CI/CD configuration.

Requirement (2) requires that the network not be enforced as the only possible source of new configuration.

## Proposed API

We propose the introduction of a new export from Cerebro called `ConfigPoller`. An instance of `ConfigPoller` can be given to a `Cerebro` object for it to react to the appearance of new configuration.

Example:

```js
import Cerebro, {ConfigPoller} from 'cerebro';

const cerebro = new Cerebro(config, {
  poller: new ConfigPoller({
    fetcher: async () => {
      const response = await fetch(fetchConfig);
      
      return response.json();
    },
    interval: 1 * 60 * 1000
  });
});
```

The `ConfigPoller` object would fire an event called `update` that would contain a candidate for new config. Cerebro would then revalidate the new config.

Alternatively this can be done by adding more specialized configuration to `Cerebro`. I'm OK with both options, this just keeps the API surface area of base Cerebro cleaner.

**Comment by scsper** [comment]
looks fine to me, as long as the poller is optional

**Comment by scsper** [comment]
@jlecomte has more skin in the game than i do though

**Comment by juandopazo** [comment]
Pull request: https://github.com/yahoo/cerebro/pull/16
